# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: social_network_db
      MYSQL_USER: social_network_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  mysql_data:
